### ISSUE TITLE
Use binaries from upstream traefik releases

### ISSUE THREAD

**Issue by mmanciop** [jnsgruk/traefik-rock#3]

**Comment by jnsgruk** [comment]
For the moment at least, I intend to keep this building from source. 

Though, FWIW, this can be trivially updated to do what this issue suggests:

```yaml
name: traefik
version: "2.6.3"
base: ubuntu:20.04

parts:
  # ...
  
  traefik:
    plugin: dump
    source: https://github.com/traefik/traefik/releases/download/v2.6.3/traefik_v2.6.3_linux_amd64.tar.gz
    override-build: |
      mkdir -p $CRAFT_PART_INSTALL/usr/bin
      cp traefik $CRAFT_PART_INSTALL/usr/bin/traefik
```
